cask_args appdir: '/Applications'
tap 'caskroom/cask'
tap 'telemachus/brew', 'https://telemachus@bitbucket.org/telemachus/brew.git'
tap 'caskroom/homebrew-versions'
brew 'redis', restart_service: true
brew 'mysql'
brew 'git'
brew 'macvim'
brew 'postgresql'
brew 'tmux'
brew 'tomcat'
brew 'vim'
brew 'wget'
brew 'zsh'
brew 'curl'
brew 'colordiff'
brew 'tomcat'
brew 'brew-pip'
cask 'google-chrome'
cask 'java' unless system '/usr/libexec/java_home --failfast'
cask 'sublime-text3'
cask 'alfred'
cask 'sourcetree'
cask 'iterm2'
cask 'google-japanese-ime'
cask 'google-drive'
cask 'dropbox' 
cask 'evernote'
cask 'clipy'
cask 'pg-commander'
cask 'sequel-pro'
cask 'unity'
cask 'android-studio'
cask 'vlc'
cask 'python'
cask 'atom'
cask 'gimp'
cask 'xquartz'
cask 'inkscape'
