code --install-extension akamud.vscode-javascript-snippet-pack
code --install-extension alefragnani.Bookmarks
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension davidhouchin.whitespace-plus
code --install-extension dbaeumer.vscode-eslint
code --install-extension DennisVash.summer-time
code --install-extension diff001a.kawaii-theme
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension jcbuisson.vue
code --install-extension jolaleye.horizon-theme-vscode
code --install-extension KishoreIthadi.dotnet-core-essentials
code --install-extension leizongmin.node-module-intellisense
code --install-extension mathiasfrohlich.Kotlin
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-mssql.mssql
code --install-extension ms-python.python
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.Go
code --install-extension nadako.vshaxe
code --install-extension octref.vetur
code --install-extension patricklee.vsnotes
code --install-extension RalfZhang.filetemplate
code --install-extension redhat.java
code --install-extension richardwillis.vscode-gradle
code --install-extension Shan.code-settings-sync
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wayou.vscode-icons-mac
code --install-extension wayou.vscode-todo-highlight
code --install-extension whizkydee.material-palenight-theme
code --install-extension xabikos.JavaScriptSnippets
